name:                SAlg
version:             0.1.0.0
github:              "session-arr/session-arr"
license:             BSD3
author:              "session-arrow"
maintainer:          "session.arrow@gmail.com"
copyright:           "2019 ANONYMISED"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/session-arr/session-arr#README.md>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.6 && < 0.7
- mtl >= 2.2 && < 2.3
- language-c >= 0.8 && < 0.9
- pretty >= 1.1 && < 1.2
- prettyprinter >= 1.2 && < 1.3
- hint >= 0.9 && < 1.0
- filepath >= 1.4 && < 1.5
- extra >= 1.6 && < 1.7

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Werror
  - -O2
  exposed-modules:
  - Control.CCat
  - Control.CArr
  - Control.CArr.CSyn
  - Control.Monad.CGen
  - Data.C
  - Language.Alg
  - Language.SPar
  - Language.SPar.Skel
  - Language.SPar.Compiler

executables:
  session-arrc:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - SAlg

# tests:
#   SAlg-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - SAlg
